"""create core tables

Revision ID: 0001
Revises:
Create Date: 2026-10-01 01:42:36.483316
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('source_filename', sa.String(), nullable=False),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.Column('ocr_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('parse_status', sa.String(), server_default='pending', nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("ocr_status IN ('pending','processing','completed','failed')", name=op.f('ck_documents_ocr_status')),
    sa.CheckConstraint("parse_status IN ('pending','completed','failed')", name=op.f('ck_documents_parse_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_table('document_pages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('ocr_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('page_number >= 1', name=op.f('ck_document_pages_page_number')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_pages_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_pages')),
    sa.UniqueConstraint('document_id', 'page_number', name=op.f('uq_document_pages_document_id'))
    )
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_pages_document_id'), ['document_id'], unique=False)

    op.create_table('document_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('section_title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_document_sections_document_id_documents')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_sections'))
    )
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_sections_document_id'), ['document_id'], unique=False)

    op.create_table('handover_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('procedure', sa.Text(), nullable=True),
    sa.Column('precaution', sa.Text(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=True),
    sa.Column('frequency', sa.String(), nullable=True),
    sa.Column('related_system', sa.String(), nullable=True),
    sa.Column('contact_info', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('importance BETWEEN 1 AND 5', name=op.f('ck_handover_items_importance')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_handover_items_document_id_documents')),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], name=op.f('fk_handover_items_section_id_document_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_handover_items'))
    )
    with op.batch_alter_table('handover_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_handover_items_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_handover_items_section_id'), ['section_id'], unique=False)

    op.create_table('questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('choices_json', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('difficulty', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("question_type IN ('multiple_choice','short_answer')", name=op.f('ck_questions_question_type')),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], name=op.f('fk_questions_document_id_documents')),
    sa.ForeignKeyConstraint(['section_id'], ['document_sections.id'], name=op.f('fk_questions_section_id_document_sections')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_questions'))
    )
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_questions_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_questions_section_id'), ['section_id'], unique=False)

    op.create_table('scoring_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('user_answer', sa.Text(), nullable=False),
    sa.Column('score', sa.REAL(), nullable=False),
    sa.Column('is_correct', sa.Boolean(create_constraint=True, name='is_correct'), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('scoring_method', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("scoring_method IN ('llm','python_fallback')", name=op.f('ck_scoring_results_scoring_method')),
    sa.CheckConstraint('score BETWEEN 0 AND 100', name=op.f('ck_scoring_results_score')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], name=op.f('fk_scoring_results_question_id_questions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_results'))
    )
    with op.batch_alter_table('scoring_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scoring_results_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scoring_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scoring_results_question_id'))

    op.drop_table('scoring_results')
    with op.batch_alter_table('questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_questions_section_id'))
        batch_op.drop_index(batch_op.f('ix_questions_document_id'))

    op.drop_table('questions')
    with op.batch_alter_table('handover_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_handover_items_section_id'))
        batch_op.drop_index(batch_op.f('ix_handover_items_document_id'))

    op.drop_table('handover_items')
    with op.batch_alter_table('document_sections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_sections_document_id'))

    op.drop_table('document_sections')
    with op.batch_alter_table('document_pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_pages_document_id'))

    op.drop_table('document_pages')
    op.drop_table('documents')
    # ### end Alembic commands ###
